name: Terraform Validation

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Run Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: ./infrastructure
        run: terraform init

      - name: Format Check
        working-directory: ./infrastructure
        run: terraform fmt -check -recursive

      - name: Validate Terraform
        working-directory: ./infrastructure
        run: terraform validate

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        working-directory: ./infrastructure
        run: tflint || true

